version: 2.1

executors:
  linux-node:
    docker:
      - image: cimg/node:20.5
    working_directory: ~/repo

  macos-node:
    macos:
      xcode: "14.3.1"
    working_directory: ~/repo

jobs:
  build-linux:
    executor: linux-node
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            sudo apt update
            sudo apt install -y build-essential libx11-dev libgl1-mesa-dev libgtk-3-dev
      - run:
          name: Build static wxWidgets (cached in deps/wxWidgets)
          command: |
            mkdir -p deps
            cd deps
            git clone --depth=1 https://github.com/wxWidgets/wxWidgets.git
            cd wxWidgets
            mkdir build && cd build
            ../configure --disable-shared --enable-unicode --with-gtk=3 --prefix=$(pwd)/../dist
            make -j$(nproc)
            make install
      - run:
          name: Build prebuilt binary
          command: |
            export CXXFLAGS="-I$(pwd)/deps/wxWidgets/dist/include"
            export LDFLAGS="-L$(pwd)/deps/wxWidgets/dist/lib"
            npm install
            npm run prebuild
      - persist_to_workspace:
          root: .
          paths:
            - prebuilds

  build-macos:
    executor: macos-node
    steps:
      - checkout
      - run:
          name: Install wxWidgets via Homebrew
          command: |
            brew install wxwidgets
      - run:
          name: Build prebuilt binary
          command: |
            export CXXFLAGS="$(wx-config --cxxflags)"
            export LDFLAGS="$(wx-config --libs)"
            npm install
            npm run prebuild
      - persist_to_workspace:
          root: .
          paths:
            - prebuilds

  publish-npm:
    executor: linux-node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with NPM
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Publish to NPM
          command: |
            npm publish --access public

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build-linux
      - build-macos
      - publish-npm:
          requires:
            - build-linux
            - build-macos
